MONGO_SERVER: localhost
MONGO_DB: reading-is-good
MONGO_AUTO_INDEX: true

RABBIT_NODES: localhost
RABBIT_PORT: 5672
RABBIT_USER: guest
RABBIT_PASS: guest

REDIS_SERVER: localhost:6379
REDIS_DEFAULT_DB: 0
REDIS_LOCK_TIMEOUT: 30s

JWT_ACCESS_SECRET_KEY: 9a0b7e65-1f29-44a5-ac2e-592b55fec006
JWT_ACCESS_EXPIRATION: 5m
JWT_REFRESH_EXPIRATION: 10m
JWT_REFRESH_SECRET_KEY: 0dbedfae-f25c-4e46-adce-2caead994db8
JWT_ISSUER: reading-is-good
server:
  port: 8080
