FROM maven:3.8.5-openjdk-18 AS build

COPY ./ /app/

RUN mvn -f /app/framework/pom.xml clean install

RUN mvn -f /app/reading-is-good/pom.xml clean install -DskipTests

FROM openjdk:18-alpine
COPY --from=build /app/reading-is-good/api/target/api-1.0-SNAPSHOT.jar /usr/local/lib/application.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/local/lib/application.jar"]
