version: '2.4'

services:
   rig-api:
      image: rig-api
      container_name: rig-api
      restart: on-failure:3
      depends_on:
         - mongo-db
         - rabbit-mq
         - redis
      ports:
         - 8080:8080
      environment:
        - "SPRING_PROFILES_ACTIVE=test"
      networks:
         - getir
   rabbit-mq:
      image: rabbitmq:3-management
      container_name: rabbit-mq
      restart: on-failure:3
      ports:
         - "5672:5672"
         - "15672:15672"
      expose:
         - 5672
         - 15672
      environment:
        - "RABBITMQ_DEFAULT_USER=user"
        - "RABBITMQ_DEFAULT_PASS=password"
      networks:
         - getir
   redis:
      image: redis
      container_name: redis
      restart: on-failure:3
      ports:
         - 6379:6379
      expose:
         - 6379
      networks:
         - getir
   mongo-db:
      image: mongo
      container_name: mongo-db
      restart: on-failure:3
      command: mongod --replSet rs0
      ports:
         - 27017:27017
      expose:
         - 27017
      networks:
         - getir
   mongo-rs-initiator:
      image: mongoclient/mongoclient
      restart: "no"
      depends_on:
         - mongo-db
      networks:
         - getir
      command: mongo --host mongo-db:27017 --eval 'rs.initiate();' 
networks:
   getir:
      driver: bridge